### PR TITLE
Fix watcher merge issue

### PR DESCRIPTION
**Pull request by cs-shadow**
Note: All credit (or blame, as the case be) should go to @aevri. I'm merely creating the PR from his commits.

### CODE REVIEW

**Comment by cs-shadow** [comment]
I'm not sure why the `Fix watcher merge issue` commit is appearing above the other two but its definitely after the other two in the actual commit history. Although the Travis build was triggered on the correct commit so seems like a bug in Github UI

**Comment by cs-shadow** [comment]
Update according to changes in #60 and fixed an issue in merging of new urls.

**Comment by cs-shadow** [comment]
@aevri This is ready for review for now - moved `git_fetch_counter_arcyd.py` to `testbed/arcyd` and converted hardcoded script location to be more variable-based.

**Comment by aevri** [comment]
Excellent, thank you very much!

**Pull request merged**
