### PR TITLE
Arcyd: Extract common arguments to arcyd into a function

### PR DESCRIPTION
**Pull request by cs-shadow**
py/abd/abdcmd_init.py and py/abd/abdi_processrepoarglist.py both add
similar arguments to the parser which results in code duplication.
Extract the addition of arguments which are common to both files into a
function so that the same function can be called from both places. Also,
add max_workers as an argument to py/abd/abdcmd_init.py.

Testplan:
$ ./precommit.sh

### CODE REVIEW

**Comment by cs-shadow** [comment]
This should not be merged until #28 gets in

**Comment by cs-shadow** [comment]
@aevri Your comments got lost because you commented on the individual commit so in future lets try to avoid commenting on commits so that they don't get lost after rebasing etc. Also, fixed your concerns now - no underscore in function name and removed max_workers from abdcmd_init to be added later.

**Comment by cs-shadow** [comment]
Fixed a minor typo.

**Comment by aevri** [comment]
LGTM, thanks! Landed at e89214d

**Pull request closed without merging**
