### PR TITLE
Add arcyon git-diff-helper command

### PR DESCRIPTION
**Pull request by sstriker**
* bin/arcyon: Expand search path
* py/aon/aoncmd_arcyon.py: Add git-diff-helper command.
* py/aon/aoncmd_gitdiffhelper.py: New diff helper,
  leveraging abdt_differ.
* py/aon/README.md
* doc/man/arcyd/arcyd.generated.txt
* doc/man/arcyd/arcyon.generated.txt
  Update documentation
* meta/package_deps/expected-package-deps
  Update deps for aoncmd

Test Plan:
    $ ./precommit.sh

### CODE REVIEW

**Comment by sstriker** [comment]
Processed review comments and updated the pull request.

**Comment by aevri** [comment]
Great! Please also re-run `./precommit.sh`

**Comment by aevri** [comment]
Ah you did, my mistake :)

**Comment by aevri** [comment]
Ok this is good to go, will land at next opportunity. Thanks!

**Pull request closed without merging**
